### PR TITLE
Issue/3

### LINKED ISSUE #3: Implement LIC1
Implement associated test case.

### PR DESCRIPTION
**Pull request by Lussebullen**
Implemented Lic1 and associated test cases.
Helper methods are included for better readability of Lic1 code.

fixes #3

### CODE REVIEW

**Comment by Omar-AV** [comment]
LGTM with one exception, when verifying that `NUMPOINTS` is a valid shouldn't number 0 be allowed? I.e. in `LicAnalyzer.java` on line 78: `(n < 0)` rather than `(n < 1)`? My reasoning is that the LIC can still evaluate no points and conclude that its requirements are not met.

**Comment by asirago** [comment]
As per the assignment instructions`2 <= NUMPOINTS <= 100` 

Make sure to include the upper limit like so `(n < 0 || n > 98)`

**Comment by Omar-AV** [comment]
> As per the assignment instructions`2 <= NUMPOINTS <= 100`
> 
> Make sure to include the upper limit like so `(n < 0 || n > 98)`

Missed this myself, since this is the case my initial comment on this pull request probably cease to matter. Sorry.

**Review by empazi — APPROVED** [review]
LGTM

**Pull request closed without merging**
